# USERS
POST http://localhost:3000/users/create
content-type: application/json

{
    "username": "Tester",
    "password": "123"   
}

###

GET http://localhost:3000/users/

###

# AUTH
POST http://localhost:3000/login
content-type: application/json

{
    "username": "Tester",
    "password": "123"
}

###

GET http://localhost:3000/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3RlciIsInN1YiI6MiwiaWF0IjoxNjQzNjEyMDIxLCJleHAiOjE2NDM2MTI2MjF9.ie92D0liJ-xiJHlnC3oTELnv0cSN7BpLK6aMoot-zac



### TODO
POST http://localhost:3000/todo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3RlciIsInN1YiI6MSwiaWF0IjoxNjQzNjI1OTI4LCJleHAiOjE2NDM2MjY1Mjh9.45otqIJWOURpSatxx_9Y8qiu3ThGecIf6RyASrzyDOc
content-type: application/json

{
    "name": "Tester task 2"
}

###
GET http://localhost:3000/todo/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3RlciIsInN1YiI6MSwiaWF0IjoxNjQzNjIyMzIzLCJleHAiOjE2NDM2MjI5MjN9.xkw1Lqmx2qRTpJaK0n1GEV8k73lAdJVplzta3la8I0s


###
POST http://localhost:3000/todo/1/done
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3RlciIsInN1YiI6MSwiaWF0IjoxNjQzNjIyMzIzLCJleHAiOjE2NDM2MjI5MjN9.xkw1Lqmx2qRTpJaK0n1GEV8k73lAdJVplzta3la8I0s


###
POST http://localhost:3000/todo/1/status
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3RlciIsInN1YiI6MSwiaWF0IjoxNjQzNjIyMzIzLCJleHAiOjE2NDM2MjI5MjN9.xkw1Lqmx2qRTpJaK0n1GEV8k73lAdJVplzta3la8I0s
